### ISSUE TITLE
キャラクターの上を通過できる

### ISSUE THREAD

**Issue by uwatcha** [CreativeAI2024/CreativeAI2024#108]
**概要**

キャラクターに当たり判定がなく、通過できてしまうのは違和感

**詳細**
再現方法:
1. 
2. 

エラー文:
```

```

**スクリーンショット**

![スクリーンショット 2024-12-04 18 55 29](https://github.com/user-attachments/assets/4493704c-da8f-4830-9dd4-35c0d84fcaed)

**発生機材:**
 - OS: [Mac]

**補足事項**

- 特になし

**Comment by kanata0510** [comment]
#155 と重複したのでClose
