### ISSUE TITLE
フォントが適用されていない

### ISSUE THREAD

**Issue by uwatcha** [CreativeAI2024/CreativeAI2024#113]
**概要**

develop最新版でそうなっている
**詳細**
再現方法:
1. 
2. 

エラー文:
```

```

**スクリーンショット**

**発生機材:**
 - OS: [Windows or Mac]

**補足事項**

- 特になし

**Comment by kanata0510** [comment]
どこのフォントが適用されていないのかもう少し詳しく教えてほしい

**Comment by kanata0510** [comment]
#114で直すのでクローズ
