### ISSUE TITLE
アイテム名

### ISSUE THREAD

**Issue by b1022226** [CreativeAI2024/CreativeAI2024#114]
**概要**

**詳細**
再現方法:
1. cでアイテム画面を開く

エラー文:
```

```

**スクリーンショット**
![image](https://github.com/user-attachments/assets/b4b82673-cffd-4f1d-b7fd-ed3eefb0f712)

**発生機材:**
 - OS: [Windows]

**補足事項**

- 特になし

**Comment by uwatcha** [comment]
#113 
が原因と思われる
