### ISSUE TITLE
tessen_roomに何もない/何も起こらない

### ISSUE THREAD

**Issue by uwatcha** [CreativeAI2024/CreativeAI2024#117]
**概要**

tessen_roomにテッセンがいない。
開発中はtessen_roomの中央あたりまで進むと会話が始まった気がしたが、それが発生しない。

**詳細**
再現方法:
tessen_roomに入る

エラー文:
```

```

**スクリーンショット**

**発生機材:**
 - OS: [Mac]

**補足事項**

- 特になし

**Comment by kanata0510** [comment]
修正して確認したのでClose
