### ISSUE TITLE
「続きから」を押してゲームを再開すると、入手していたアイテムがアイテム一覧から消える。

### ISSUE THREAD

**Issue by b1022226** [CreativeAI2024/CreativeAI2024#118]
**概要**
「続きから」を押してゲームを再開すると、入手していたアイテムがアイテム一覧から消える。

**詳細**
再現方法:
1. 
2. 

エラー文:
```

```

**スクリーンショット**

**発生機材:**
 - OS: [Windows or Mac]

**補足事項**

- 特になし

**Comment by uwatcha** [comment]
学生証は消えないが、その他の入手したアイテムは消える
