### ISSUE TITLE
タイトル画面でカーソルの動作不良

### ISSUE THREAD

**Issue by uwatcha** [CreativeAI2024/CreativeAI2024#119]
**概要**

**詳細**
再現方法:
### セーブデータがない時
1. 起動する
2. この時点で「つづきから」は表示されていない
3. 下キーを入力する
4. カーソルが移動する
5. そこからカーソルを動かせない
6. この状態でZキーを入力する
7. はじめからゲームが開始する

### セーブデータがある時
1. 起動する
2. この時点で「つづきから」は表示されていない
3. 下キーを入力する
4. カーソルが移動する
5. そこからカーソルを動かせない
6. カーソルは固定されているが、内部では項目の選択が行われており、上キーを入力してからZキーを押せば「はじめから」、そのままZキーを押せば「つづきから」が行われる

エラー文:
```

```

**スクリーンショット**

![Uploading スクリーンショット 2024-12-05 11.15.23.png…]()

**発生機材:**
 - OS: [Windows or Mac]

**補足事項**

- 特になし

**Comment by 5884-u** [comment]
最新のdevelopでは治っているはず
