### ISSUE TITLE
レイの血に関するバグ

### ISSUE THREAD

**Issue by uwatcha** [CreativeAI2024/CreativeAI2024#120]
**概要**

レイの血がなぜかitemA_roomの上のドアを開けた先の部屋に落ちている
レイの血が落ちている場所にキラキラが表示されていない
レイの血を入手するときに表示されるテキストが「Rei's Bloodを入手した」になっている

**詳細**
再現方法:
1. 
2. 

エラー文:
```

```

**スクリーンショット**

**発生機材:**
 - OS: [Mac]

**補足事項**

- 特になし

**Comment by 5884-u** [comment]
レイの血を入手するときに表示されるテキストが「Rei's Bloodを入手した」になっている
に関しては修正しました

**Comment by SAKUSAKU36** [comment]
レイの血はキラキラを表示しなくていいよ。
また、レイの血が床下から見つかるようにしたいので、下記のどちらかが実現出来たらよいなと思ってます。
・レイの血の配置をカーペット下に移動して、重ね合わせゲームの背景の数字も変えてもらう。
・カーペットの大きさを変更してもらい、今レイの血が配置されている位置を覆うようにする。

**Comment by uwatcha** [comment]
確認した結果、全て仕様だった
