### ISSUE TITLE
アイテム合成時の表示テキストの不良

### ISSUE THREAD

**Issue by uwatcha** [CreativeAI2024/CreativeAI2024#121]
**概要**

**詳細**
再現方法:
1. itemA_roomのソファー下のsearchGameを行う
2. 右のアイテムを拾う
3. 左のアイテムを拾う
4. 自動でアイテムを合成したことを表すテキストが表示されるが、合成したアイテムが何かは表示されない

エラー文:
```

```

**スクリーンショット**

**発生機材:**
 - OS: [Windows or Mac]

**補足事項**

- 特になし

**Comment by 5884-u** [comment]
こっちでは正常に動いているのでスクリーンショット等もっと詳細に教えてほしい
