### ISSUE TITLE
アイテム名の表示不良

### ISSUE THREAD

**Issue by uwatcha** [CreativeAI2024/CreativeAI2024#124]
**概要**

「アイテム名を入手した」
というテキストで、アイテム名が英語になっている

**詳細**
再現方法:
1. 
2. 

エラー文:
```

```

**スクリーンショット**

**発生機材:**
 - OS: [Windows or Mac]

**補足事項**

- 特になし

**Comment by kanata0510** [comment]
#114 と重複
