### ISSUE TITLE
アイテムAの部屋でソファ下をみるのを「やめる」と選択した後、BGMが消えて無音になる

### ISSUE THREAD

**Issue by SAKUSAKU36** [CreativeAI2024/CreativeAI2024#134]
**概要**

**詳細**
再現方法:
1. 
2. 

エラー文:
```

```

**スクリーンショット**

**発生機材:**
 - OS: [Windows or Mac]

**補足事項**

- 特になし

**Comment by uwatcha** [comment]
他にも、「{アイテム}を入手した。」という会話ウィンドウが表示された時もBGMが止まる.
