### ISSUE TITLE
重ね合わせゲームができない

### ISSUE THREAD

**Issue by SAKUSAKU36** [CreativeAI2024/CreativeAI2024#144]
**概要**

**詳細**
再現方法:
1. アイテムBの部屋の左上にある机でEnterキーを押す
2. 

エラー文:
```

```

**スクリーンショット**

**発生機材:**
 - OS: [Windows or Mac]

**補足事項**

- 特になし

**Comment by uwatcha** [comment]
黒いカードを入手した後に呼び出せた
