### ISSUE TITLE
テーブルの下のサーチゲームができない

### ISSUE THREAD

**Issue by SAKUSAKU36** [CreativeAI2024/CreativeAI2024#148]
**概要**

**詳細**
再現方法:
1. 
2. 

エラー文:
```

```

**スクリーンショット**

**発生機材:**
 - OS: [Windows or Mac]

**補足事項**

- 特になし

**Comment by kanata0510** [comment]
@SAKUSAKU36 状況をもう少し詳しく教えてほしい
