### ISSUE TITLE
鏡の上部からの当たり判定に違和感を感じる

### ISSUE THREAD

**Issue by SAKUSAKU36** [CreativeAI2024/CreativeAI2024#164]
**概要**

**詳細**
再現方法:
1. 
2. 

エラー文:
```

```

**スクリーンショット**

**発生機材:**
 - OS: [Windows or Mac]

**補足事項**

- 特になし

**Comment by kanata0510** [comment]
#145 と重複してそう

**Comment by kanata0510** [comment]
なのでClose
